---
title: "Rothia Species Characterization"
output: html_document
date: "2025-03-13"
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
```

```{r load data, include=FALSE}
# ANI and dDDH results
rothia_ANI_dDDH_results <- read_csv("./derivedData/rothia_ANI_dDDH_results.csv")

# BiG-SCAPE results
bigscape_results <- read.table("./derivedData/multismash_out/bigscape/absence_presence_clean.tsv", header = TRUE, row.names = 1)
```

```{r set order, include=FALSE}
rothia_order <- c("P31", "257", "36", "ATCC27570", "CCTCCAB206069", "CCUG35957", 
                  "YIM67072", "LMG23708", "140917MRSA09", "J18", "A117B", "ATCC17931", 
                  "576267", "RSM386", "RSM292", "RSM407", "RSM42")
```

```{r processing dDDH data, include=FALSE}
# dDDH
## subset to dDDH results
rothia_ANI_dDDH_results_dDDH <- rothia_ANI_dDDH_results %>%
  select(query, target, DDH)

## reorder to correspond to phylogenetic tree
rothia_ANI_dDDH_results_dDDH$query <- factor(rothia_ANI_dDDH_results_dDDH$query, levels = rothia_order)
rothia_ANI_dDDH_results_dDDH$target <- factor(rothia_ANI_dDDH_results_dDDH$target, levels = rothia_order)
```

```{r processing ANIb data, include=FALSE}
#ANIb
## subset to ANIb results
rothia_ANI_dDDH_results_ANIb <- rothia_ANI_dDDH_results %>%
  select(query, target, ANIb)

# reorder to correspond to phylogenetic tree
## reorder to correspond to phylogenetic tree
rothia_ANI_dDDH_results_ANIb$query <- factor(rothia_ANI_dDDH_results_ANIb$query, levels = rothia_order)
rothia_ANI_dDDH_results_ANIb$target <- factor(rothia_ANI_dDDH_results_ANIb$target, levels = rothia_order)
```

```{r processing ANIm data, include=FALSE}
#ANIm
## subset to ANIb results
rothia_ANI_dDDH_results_ANIm <- rothia_ANI_dDDH_results %>%
  select(query, target, ANIm)

## reorder to correspond to phylogenetic tree
rothia_ANI_dDDH_results_ANIm$query <- factor(rothia_ANI_dDDH_results_ANIm$query, levels = rothia_order)
rothia_ANI_dDDH_results_ANIm$target <- factor(rothia_ANI_dDDH_results_ANIm$target, levels = rothia_order)
```

```{r processing BiG-SCAPE data, include=FALSE}
#BiG-SCAPE
## perform a hierarchical clustering
bgc_hclust <- hclust(dist((bigscape_results), method = "euclidean"), method = "ward.D2")
bgc_hclust_2 <- hclust(dist(t(bigscape_results), method = "euclidean"), method = "ward.D2")

## convert the matrix into tidy format
bgc_matrix <- rownames_to_column(bigscape_results, "strain")

bgc_matrix <- bgc_matrix %>%
  pivot_longer(!strain, names_to="component", values_to = "Presence")

## reorder based on hierarchical clustering
bgc_matrix$strain <- factor(bgc_matrix$strain, levels = (bgc_hclust$labels)[bgc_hclust$order])
bgc_matrix$component <- factor(bgc_matrix$component, levels = (bgc_hclust_2$labels)[bgc_hclust_2$order])

## convert to factor
bgc_matrix$Presence <- factor(bgc_matrix$Presence)

## adjust the names
custom_labels <- c("P31", "257", "36", "ATCC 27570", "CCTCC AB 206069", "CCUG 35957", 
  "YIM 67072", "LMG 23708", "140917-MRSA-009", "J18", "A1-17B", "ATCC 17931", 
  "5762/67", "RSM386", "RSM292", "RSM407", "RSM42")

names(custom_labels) <- c("P31", "257", "36", "ATCC27570", "CCTCCAB206069", "CCUG35957", 
  "YIM67072", "LMG23708", "140917MRSA09", "J18", "A117B", "ATCC17931", 
  "576267", "RSM386", "RSM292", "RSM407", "RSM42")
```

```{r gg_theme, include=FALSE, echo=FALSE}
# standard theme for all ggplot objects
gg_theme <- theme_classic() +
  theme(axis.text.y = element_text(color = "black"),
        axis.text.x = element_text(color = "black"),
        axis.ticks.y = element_line(color = "black", linewidth = 0.25),
        axis.ticks.x = element_line(color = "black", linewidth = 0.25), 
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth = 0.25),
        plot.background = element_blank(),
        legend.position = "none",
        legend.title=element_blank(),
  )
```

```{r dDDH heatmap, include=FALSE}
# dDDH heat map figure
dDDH_heatmap <- ggplot(data = rothia_ANI_dDDH_results_dDDH, aes(x = query, y = target, fill = DDH)) +
  gg_theme +
  geom_tile() +
  scale_fill_gradient(limits = c(10, 100), 
                       breaks = c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100), 
                       labels = c("10%", "20%", "30%", "40%", "50%","60%","70%", "80%", "90%", "100%")) +
  theme(legend.position = "bottom",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(fill = "dDDH (%)")

dDDH_heatmap
```

```{r ANIb heatmap, include=FALSE}
# ANIb heat map figure
ANIb_heatmap <- ggplot(data = rothia_ANI_dDDH_results_ANIb, aes(x = query, y = target, fill = ANIb)) +
  gg_theme +
  geom_tile() +
  scale_fill_gradient(limits = c(70, 100), 
                       breaks = c(70, 80, 90, 100), 
                       labels = c("70%", "80%", "90%", "100%")) +
  theme(legend.position = "bottom",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(fill = "ANIb (%)")

ANIb_heatmap
```

```{r ANIm heatmap, include=FALSE}
# ANIm heat map figure
ANIm_heatmap <- ggplot(data = rothia_ANI_dDDH_results_ANIm, aes(x = query, y = target, fill = ANIm)) +
  gg_theme +
  geom_tile() +
  scale_fill_gradient(limits = c(80, 100), 
                       breaks = c(80, 90, 100), 
                       labels = c("80%", "90%", "100%")) +
  theme(legend.position = "bottom",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(fill = "ANIm (%)")

ANIm_heatmap
```

```{r BGC heatmap, include=FALSE}
BGC_heatmap <- ggplot(data = bgc_matrix, aes(x = strain, y = component, fill = Presence)) +
  gg_theme +
  geom_tile() +
  scale_x_discrete(labels = custom_labels) +
  scale_fill_manual(values = c("0" = "white", "1" = "black")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        aspect.ratio = 1,
        axis.text.y = element_text(size = 8)) +
  xlab("Strain") +
  ylab("Gene Cluster Family")

BGC_heatmap

ggsave("./figures/rothia_bgc_heatmap.pdf", BGC_heatmap, units = c("in"), height = 6.46, width = 4)

```

